[package]
name = "uwuifier"
version = "0.1.0"
edition = "2021"

[dependencies]
tinyrand = "0.5.0" # tiny rand is very fast
xxhash-rust = { version = "*", features = ["xxh3"] } # and dis thingy too

[dev-dependencies]
criterion = "0.5.1"

# keep your code optimized 😊❤️
[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
panic = "abort"
lto = true
strip = true
incremental = true
codegen-units = 1
